<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle($this->translate('Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer...'))->setSeparator(' | ')->setAutoEscape(false); ?>

  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet($this->basePath() . '/css/main.css'); ?>

  <?php echo $this->headScript()->prependFile($this->basePath().'/js/vendor/modernizr-2.6.2.min.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
<body id="<?php echo ((isset($this->bodyID) ? $this->bodyID : 'page')); ?>">
  <!--[if lt IE 7]><p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p><![endif]-->

  <!--main body-->
  <div id="wrapper" class="clearfix">
    <?php echo $this->content; ?>
    <footer class="clearfix">
      &copy; <?php echo date('Y'); ?> <a href="mailto:jonzielen@gmail.com">jon zielenkievicz</a>
    </footer>
  </div>
  <!--.main body-->

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
  <?php echo $this->inlineScript()
      ->prependFile($this->basePath() . '/js/main.min.js')
      ->prependFile($this->basePath() . '/js/plugins.min.js') ?>

  <!-- Google Analytics -->
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-45577096-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

</body>
</html>
