<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle($this->translate('Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer...'))->setSeparator(' | ')->setAutoEscape(false); ?>

  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet($this->basePath() . '/css/main.css'); ?>

  <?php echo $this->headScript()->prependFile($this->basePath().'/js/vendor/modernizr-2.6.2.min.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
<body id="<?php echo ((isset($this->bodyID) ? $this->bodyID : 'page')); ?>">
  <!--[if lt IE 7]><p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p><![endif]-->

  <!--main body-->
  <div id="wrapper" class="clearfix">
    <?php echo $this->content; ?>
    <footer class="clearfix">
      &copy; <?php echo date('Y'); ?> <a href="mailto:jonzielen@gmail.com">jon zielenkievicz</a>
    </footer>
  </div>
  <!--.main body-->

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
  <?php echo $this->inlineScript()
      ->prependFile($this->basePath() . '/js/main.js')
      ->prependFile($this->basePath() . '/js/plugins.js') ?>

  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-45577096-1', 'zielenkievicz.com');
    ga('send', 'pageview');
  </script>
</body>
</html>
