<?php
  $title = 'Html Emails';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'html emails, html email, web developer, jon zielenkievicz');
  $this->headMeta()->appendName('description', 'Html emails built by Jon Zielenkievicz.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link">Jon Zielenkievicz <span id="hp-logo-sub">- an html5, css3, jquery, javascript, php, mysql explorer...</span></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section class="clearfix">
    <article class="clearfix">
      <figure>
        <h2>African Wildlife Foundation</h2>
        <a href="http://www.awf.org/landing/2013-12/holiday1.html" target="_blank" class="notMmaintained slide"><img src="/img/html-email/awf-2013-12.jpg" alt="African Wildlife Foundation" /></a>
      </figure>

      <figure>
        <h2>Northeast Animal Shelter</h2>
        <a href="http://www.northeastanimalshelter.org/scoop/email/2013_11_hol_ecard/2013_11_ecard2.html" target="_blank" class="notMmaintained slide"><img src="/img/html-email/neas-2013-12.jpg" alt="Northeast Animal Shelter" /></a>
      </figure>

      <figure>
        <h2>Freedom From Hunger</h2>
        <a href="http://sankynet.mkt5124.com/2013-11-Thanksgiving-Email-2/" target="_blank" class="notMmaintained slide"><img src="/img/html-email/ffh-2013-12.jpg" alt="Northeast Animal Shelter" /></a>
      </figure>
    </article>
  </section>
</div>
