<?php
  $this->headMeta()->appendName('keywords', 'html5, css3, jquery, javascript, php, mysql, object oriented programming, git, web developer');
  $this->headMeta()->appendName('description', 'Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql, object oriented programming, git, web developer');
?>
<header class="clearfix">
  <h1 id="hp-logo"><?php echo $this->motto; ?></h1>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <section>
    <article class="clearfix">
      <h2>Welcome!</h2>
      <p>As Web Developer for <a href="http://www.flycommunications.com/" target="_blank">Fly Communications</a>, my goal is to build dynamic web sites, using best practices (in html, css, php, javascript, mysql, image compression) while optimizing page performance for end users, all with an eye toward SEO.</p>
      <p>From 2008 to 2013 I worked at <a href="http://sankyinc.com/" target="_blank">Sanky Communications</a> developing web sites.</p>
      <p>I enjoy building web sites, pages and html emails using html5, css3, jquery and php. Within these pages you will find some examples of my work.</p>
      <p class="italic">Enjoy!</p>
    </article>
  </section>
</div>
