<?php
  $title = 'Landing Pages';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'landing pages, html5, css3, jquery, compass');
  $this->headMeta()->appendName('description', 'Landing Pages built with html5, css3, jquery and compass.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link"><?php echo $this->motto; ?></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Readership</h2>
        <a href="http://readershipmusic.com/" target="_blank"><img src="/img/landing/readership/readership-landing.jpg" alt="Readership" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Backstretch</li>
            <li>Compass</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Design/build/maintain</li>
            <li>Compress CSS</li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>World Society for the Protection of Animals</h2>
        <a href="http://wspa.thankyou4caring.org/sanky-sem-and-social/lapsed-donor-video-landing-pages/bears" target="_blank" class="notMmaintained"><img src="/img/landing/wspa/wspa-dogs.jpg" alt="World Society for the Protection of Animals" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build and maintain page.</li>
          </ul>
        </figcaption>
      </figure>

      <figure class="lastFig">
        <h2>World Society for the Protection of Animals</h2>
        <a href="https://wspa.thankyou4caring.org/help-end-dog-abuse-1" target="_blank" class="notMmaintained"><img src="/img/landing/wspa/wspa-bears.jpg" alt="World Society for the Protection of Animals" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build and maintain page.</li>
          </ul>
        </figcaption>
      </figure>

    </article>
  </section>
</div>
