<?php
  $title = 'Links';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'links, git, github, html5 boilerplate, compass, php, zend');
  $this->headMeta()->appendName('description', 'Pages I find useful.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link"><?php echo $this->motto; ?></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <h2>View My Code:</h2>
      <ul>
        <li><a href="https://github.com/jonzielen?tab=repositories" target="_blank">https://github.com/jonzielen</a></li>
      </ul>

      <h2>Online:</h2>
      <ul>
        <li><a href="http://www.linkedin.com/in/jonzielenkievicz" target="_blank">http://www.linkedin.com/in/jonzielenkievicz</a></li>
      </ul>

      <h2>Work Experience:</h2>
      <ul>
        <li><a href="/doc/Jonathan-Zielenkievicz-Resume.pdf" target="_blank">Resume</a></li>
      </ul>

      <h2>Resource I Use:</h2>
      <ul>
        <li><a href="http://html5boilerplate.com/" target="_blank">http://html5boilerplate.com/</a></li>
        <li><a href="http://compass-style.org/" target="_blank">http://compass-style.org/</a></li>
        <li><a href="http://www.fontsquirrel.com/" target="_blank">http://www.fontsquirrel.com/</a></li>
        <li><a href="http://php.net/"target="_blank">http://php.net/</a></li>
        <li><a href="http://framework.zend.com/" target="_blank">http://framework.zend.com/</a></li>
        <li><a href="https://github.com/" target="_blank">https://github.com/</a></li>
        <li><a href="http://www.sublimetext.com/" target="_blank">http://www.sublimetext.com/</a></li>
        <li><a href="http://stackoverflow.com/" target="_blank">http://stackoverflow.com/</a></li>
        <li><a href="http://www.smashingmagazine.com/" target="_blank">http://www.smashingmagazine.com/</a></li>
      </ul>

      <h2>Contact:</h2>
      <ul>
        <li><a href="mailto:jonzielen@gmail.com">jonzielen@gmail.com</a></li>
      </ul>
    </article>
  </section>
</div>
