<?php
  $title = 'Responsive';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'responsive web site, html5, css3');
  $this->headMeta()->appendName('description', 'Responsive web sites built with html5, css3, and jquery by Jon Zielenkievicz.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link">Jon Zielenkievicz <span id="hp-logo-sub">- an html5, css3, jquery, javascript, php, mysql explorer...</span></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>African Wildlife Foundation</h2>
        <a href="https://my.awf.org/support-african-wildlife" target="_blank"><img src="/img/responsive/awf-support.jpg" alt="African Wildlife Foundation" /></a>
        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>
    </article>
  </section>
</div>
