<?php
  $title = 'Responsive';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'responsive web site, html5, css3');
  $this->headMeta()->appendName('description', 'Responsive web sites built with html5, css3, and jquery by Jon Zielenkievicz.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link"><?php echo $this->motto; ?></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer...</h2>
        <a href="https://github.com/jonzielen/zielenkievicz" target="_blank"><img src="/img/sites/zielenkievicz/zielenkievicz.jpg" alt="Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer..." /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>Zend Framework 2</li>
            <li>PHP</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
            <li>Compass</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Design/build a responsive portfolio</li>
            <li>Optimize page load time:
              <ul>
                <li>Compress CSS</li>
                <li>Minimize custom JQuery</li>
                <li>Compress PNG files</li>
              </ul>
            </li>
          </ul>
        </figcaption>
      </figure>

      <figure class="lastFig">
        <h2>African Wildlife Foundation</h2>
        <a href="https://my.awf.org/support-african-wildlife" target="_blank" class="notMmaintained"><img src="/img/responsive/awf-support.jpg" alt="African Wildlife Foundation" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>
    </article>
  </section>
</div>
