<?php
  $title = 'Sites';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'web sites, html5, css3, jquery');
  $this->headMeta()->appendName('description', 'Web sitesbuilt with html5, css3, and jquery by Jon Zielenkievicz.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link"><?php echo $this->motto; ?></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer...</h2>
        <a href="https://github.com/jonzielen/zielenkievicz" target="_blank"><img src="/img/sites/zielenkievicz/zielenkievicz.jpg" alt="Jon Zielenkievicz - an html5, css3, jquery, javascript, php, mysql explorer..." /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>Zend Framework 2</li>
            <li>PHP</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
            <li>Compass</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Design/build a responsive portfolio</li>
            <li>Optimize page load time:
              <ul>
                <li>Compress CSS</li>
                <li>Minimize custom JQuery</li>
                <li>Compress PNG files</li>
              </ul>
            </li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child</h2>
        <div class="left launchModal slide">
          <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-1.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child" />
          <div class="slideshowbox">
            <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-2.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child - 60 Ideas" />
            <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-3.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child - Modal" />
            <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-4.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child - Sweeps" />
          </div>
        </div>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>PHP</li>
            <li>MySQL</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>JQuery</li>
            <li>Compass</li>
            <li>UglifyJS</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Add user information to MySQL table, add images to server</li>
            <li>Optimize page load time:
              <ul>
                <li>Compress CSS</li>
                <li>Minimize custom JQuery</li>
                <li>Load images on request</li>
                <li>Compress PNG files</li>
              </ul>
            </li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>Food &amp; Wine - California Always in Season</h2>
        <a href="http://www.californiasweeps.com/" target="_blank" class="left">
          <img src="/img/sites/california-sweeps/homepage.jpg" alt="Food &amp; Wine - California Always in Season" />
        </a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>PHP</li>
            <li>MySQL</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>JQuery</li>
            <li>Ajax</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Add user information to MySQL table</li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>HomeTeam - Covenant House</h2>
        <a href="http://hometeam.covenanthouse.org/" target="_blank" class="notMmaintained"><img src="/img/sites/hometeam.jpg" alt="HomeTeam - Covenant House" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>CodeIgniter</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

      <figure class="lastFig">
        <h2>Direct Marketing Fundraisers Association</h2>
        <a href="https://www.dmfa.org/" target="_blank" class="notMmaintained"><img src="/img/sites/dmfa.jpg" alt="Direct Marketing Fundraisers Association" /></a>
        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>Drupal 7</li>
            <li>HTML5</li>
            <li>Jquery</li>
          </ul>

          <h3>Project Features:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

    </article>
  </section>
</div>
