<?php
  $title = 'Sites';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'web sites, html5, css3, jquery');
  $this->headMeta()->appendName('description', 'Web sites built with html5, css3, and jquery by Jon Zielenkievicz.');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link">Jon Zielenkievicz <span id="hp-logo-sub">- an html5, css3, jquery, javascript, php, mysql explorer...</span></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child</h2>
        <a href="#sites-scholastic-modal" class="launchModal slide">
          <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-1.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child" />
          <div class="slideshowbox">
            <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-2.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child" />
            <img src="/img/sites/ultimate-backyard-fun-guide-slides/ubf-scholastic-3.jpg" alt="Ultimate Backyard Fun Guide - Scholastic Parent &amp; Child" />
          </div>
        </a>
        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>HTML5 Boilerplate</li>
            <li>CSS3</li>
            <li>Jquery</li>
            <li>Compass</li>
            <li>UglifyJS</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build an image heavy optimized site, with custom image slide shows.</li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>HomeTeam - Covenant House</h2>
        <a href="http://hometeam.covenanthouse.org/" target="_blank"><img src="/img/sites/hometeam.jpg" alt="HomeTeam - Covenant House" /></a>
        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>MVC (CodeIgniter)</li>
            <li>HTML5</li>
            <li>CSS3</li>
            <li>Jquery</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

      <figure class="lastFig">
        <h2>Direct Marketing Fundraisers Association</h2>
        <a href="https://www.dmfa.org/" target="_blank"><img src="/img/sites/dmfa.jpg" alt="Direct Marketing Fundraisers Association" /></a>
        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>Drupal 7</li>
            <li>HTML5</li>
            <li>Jquery</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

    </article>
  </section>
</div>
