<?php
  $title = 'Web Apps';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'web apps, php, zend');
  $this->headMeta()->appendName('description', 'Web Apps built by Jon Zielenkievicz');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link"><?php echo $this->motto; ?></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Jimmy Fallon Tickets</h2>
        <a href="https://github.com/jonzielen/jf-tickets" target="_blank" class="left slide">
          <img src="/img/web-apps/jimmy-fallon/jf-1.jpg" alt="The Tonight Show starring Jimmy Fallon" />
          <div class="launchModal slideshowbox">
            <img src="/img/web-apps/jimmy-fallon/jf-ticket.png" alt="Jimmy Fallon Ticket" />
          </div>
        </a>

        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>Object Oriented PHP</li>
            <li>JSON</li>
            <li>Cron</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Run app once every minute, via cron</li>
            <li>Parse JSON object for available tickets</li>
            <li>Store/remove ticket dates from list</li>
            <li>Email user ticket date/link/availability of dates that have changed status availability (either on sale or sold out)</li>
          </ul>
        </figcaption>
      </figure>

      <figure class="lastFig">
        <h2>Ryan Adams - PAXAM</h2>
        <a href="https://github.com/jonzielen/dra-page-parser" class="left" target="_blank">
          <img src="/img/web-apps/dra/paxam.jpg" alt="Ryan Adams - PAXAM" />
        </a>

        <figcaption>
          <h3>Resources:</h3>
          <ul>
            <li>Object Oriented PHP</li>
            <li>Regular Expressions</li>
            <li>Cron</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Run app once every five minutes, via cron</li>
            <li>Loop through and compile each page of the online store</li>
            <li>Use regular expressions to parse code, compile array of items (and their price/image url/title)</li>
            <li>Check titles against list of existing items</li>
            <li>Email user with list of new items (price/image/link)</li>
          </ul>
        </figcaption>
      </figure>

    </article>
  </section>
</div>
