<?php
  $title = 'Web Apps';
  $this->headTitle($title);
  $this->headMeta()->appendName('keywords', 'web apps, php, zend');
  $this->headMeta()->appendName('description', 'Web Apps built by Jon Zielenkievicz');
?>
<header class="clearfix">
  <span id="hp-logo-wrapper">
    <a href="<?php echo $this->url('home'); ?>" id="hp-link">Jon Zielenkievicz <span id="hp-logo-sub">- an html5, css3, jquery, javascript, php, mysql explorer...</span></a>
  </span>
  <nav>
    <?php echo $this->navigation('navigation')->menu(); ?>
  </nav>
</header>
<div class="body clearfix">
  <h1><?php echo $this->escapeHtml($title); ?>:</h1>
  <section>
    <article class="clearfix">
      <figure>
        <h2>Jimmy Fallon Tickets</h2>
        <div class="left launchModal slide">
          <img src="/img/web-apps/jimmy-fallon/jf-1.jpg" alt="The Tonight Show starring Jimmy Fallon" />
          <div class="slideshowbox">
            <img src="/img/web-apps/jimmy-fallon/jf-ticket.png" alt="Jimmy Fallon Ticket" />
          </div>
        </div>

        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

      <figure>
        <h2>Ryan Adams - PAXAM</h2>
        <div class="left">
          <img src="/img/web-apps/dra/paxam.jpg" alt="Ryan Adams - PAXAM" />
        </div>

        <figcaption>
          <h3>Built with:</h3>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>Blackbaud NetCommunity</li>
          </ul>

          <h3>Responsibilities:</h3>
          <ul>
            <li>Build, maintain and update site</li>
          </ul>
        </figcaption>
      </figure>

    </article>
  </section>
</div>
